In [2]:
import numpy
numpy.__version__

'1.21.5'

In [4]:
import numpy as np

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [13]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [15]:
arr = np.array([1,2,3,4,5,6,7,8])

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [18]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8])

In [19]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr2 = np.array([[1,2,3,4,5,6], [3,5,2,5,6,2]])


In [22]:
np.sort(arr2)

array([[1, 2, 3, 4, 5, 6],
       [2, 2, 3, 5, 5, 6]])

In [28]:

arr2.ndim

2

In [29]:
arr.ndim

1

In [30]:
arr2.size

12

In [31]:
arr.size

8

In [32]:
arr.shape

(8,)

In [33]:
arr2.shape

(2, 6)

In [38]:
arr3 = np.array([[[0,1,2,3],
           [4,5,6,7]],
          
           [[0,1,2,3],
            [4,5,6,7]],
          
          [[0,1,2,3],
           [4,5,6,7]]])

In [39]:
arr3.ndim

3

In [40]:
arr3.size

24

In [41]:
arr3.shape

(3, 2, 4)

In [44]:
arr4 = np.arange(6)
arr4

array([0, 1, 2, 3, 4, 5])

In [45]:
arr4.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [47]:
arr4.shape

(6,)

In [49]:
a = arr4

In [50]:
a2 = a[np.newaxis]
a2.shape

(1, 6)

In [52]:
a2 #jadi array 2D

array([[0, 1, 2, 3, 4, 5]])

In [53]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [54]:
row_vector

array([[0, 1, 2, 3, 4, 5]])

In [57]:
col_vector = a[:, np.newaxis] # : ambil semua data
col_vector.shape

(6, 1)

In [56]:
col_vector

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [58]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [60]:
b = np.expand_dims(a, axis = 1)

In [61]:
b.shape

(6, 1)

In [62]:
b


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [65]:
c = b = np.expand_dims(a, axis = 0)
c.shape

(1, 6)

In [66]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [67]:
b[b>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [68]:
b[b%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [70]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr1 = arr[3:8]
arr2

array([[1, 2, 3, 4, 5, 6],
       [3, 5, 2, 5, 6, 2]])

In [73]:
a = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
a.shape

(3, 4)

In [78]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Basic Operation

In [79]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [80]:
a.sum()

10

In [86]:
b = np.array([[1,1],[2,6]])
b

array([[1, 1],
       [2, 6]])

In [87]:
b.sum(axis = 0)

array([3, 7])

In [88]:
b.sum(axis = 1)

array([2, 8])

In [89]:
data = np.array([1,2])
data

array([1, 2])

In [90]:
ones = np.ones(2)
ones

array([1., 1.])

In [91]:
data + ones 

array([2., 3.])

In [92]:
data * ones

array([1., 2.])

In [93]:
data - ones

array([0., 1.])

In [95]:
data * 7

array([ 7, 14])

In [96]:
data.max()

2

In [97]:
data.min()

1

In [98]:
data.sum()

3

In [99]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [100]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [101]:
np.random.random((3,2))

array([[0.57245949, 0.70901224],
       [0.81259273, 0.73949052],
       [0.26060726, 0.91042681]])

In [104]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [105]:
data/ones

array([[1., 2.],
       [3., 4.]])

In [106]:
data-ones

array([[0., 1.],
       [2., 3.]])

In [114]:
a_1 = np.array([[1,2,3],[4,5,6]])
a_1.shape

(2, 3)

In [110]:
a_2 = np.array([[7,8],[9,10],[11,12]])
a_2.shape

(3, 2)

In [115]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

# MATRIX INDEXING

In [117]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [118]:
data[0]

array([1, 2])

In [120]:
data[0,1]

2

In [122]:
data[0:2, 1]

array([2, 4])

# MATRIX AGREGATION


In [123]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [124]:
data.max()

6

In [125]:
data.min()

1

In [127]:
data.sum()

21

In [128]:
data.std()

1.707825127659933

In [129]:
data.max(axis=0)

array([5, 6])

In [130]:
data.max(axis=1)

array([2, 4, 6])

# Transposing and reshaping

In [131]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [133]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [135]:
data_col = np.array([[1,2,3,4,5,6]])
data_col

array([[1, 2, 3, 4, 5, 6]])

In [136]:
data_col = data_col.T
data_col

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [138]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [141]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

# N Dimensional array

In [145]:
ndarr = np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [146]:
ndarr.shape

(2, 2, 2)

In [147]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [148]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [150]:
np.random.random((4,3,2))

array([[[0.57026078, 0.15739984],
        [0.76975667, 0.0359854 ],
        [0.03388406, 0.90722394]],

       [[0.39948493, 0.69591379],
        [0.03502597, 0.29612178],
        [0.89361467, 0.74876407]],

       [[0.75876089, 0.36213882],
        [0.81904878, 0.4687125 ],
        [0.43235792, 0.52860976]],

       [[0.88479224, 0.77895068],
        [0.1226409 , 0.46616703],
        [0.8223257 , 0.14834268]]])

# flatten N dimensional Array

In [151]:
arrflat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arrflat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [152]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [153]:
arrflat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [154]:
error = (1/n)*np.sum(np.square(observed-prediction))

NameError: name 'n' is not defined